### ISSUE TITLE
ALT+Shift+F does not format the Django HTML file

### ISSUE THREAD

**Issue by YordanPetrovDS** [monosans/djlint-vscode#10]
I added the following adjustments in the settings.json file and the extension does not do anything, the command ALT+Shift+F also is not working.

"[html]": {
  "editor.defaultFormatter": "monosans.djlint"
},
"[django-html]": {
  "editor.defaultFormatter": "monosans.djlint"
},

**Comment by monosans** [comment]
Hey!

Thanks for reporting this issue.

This should now be fixed in `v0.2.1`.

Please let me know if everything works for you now.

**Comment by YordanPetrovDS** [comment]
Also, why only work with global python package and cannot find djlint installed in virtual environment:
settings.json:
"djlint.pythonPath":"C:\\SoftUni\\_7_Python_Web_Basics_January_2022\\_10_Workshop_Part_1\\petstragram\\.venv\\Scripts\\djlint.exe", - Not working
"djlint.pythonPath":"C:\\SoftUni\\_7_Python_Web_Basics_January_2022\\_10_Workshop_Part_1\\petstragram\\.venv\\Scripts\\djlint.exe", - Not working
"djlint.pythonPath":"C:/SoftUni/_7_Python_Web_Basics_January_2022/_10_Workshop_Part_1/petstragram/.venv/Scripts/djlint.exe", - Not working
"djlint.pythonPath":"~/.venv/Scripts/djlint.exe", - Not working

**Comment by monosans** [comment]
> Also, why only work with global python package and cannot find djlint installed in virtual environment: settings.json:

Are you sure that you specify the path to the Python interpreter?

Try running `C:\SoftUni\_7_Python_Web_Basics_January_2022\_10_Workshop_Part_1\petstragram\.venv\Scripts\djlint.exe -m djlint` in the PowerShell.

I personally use `djlint` from venv, and it works fine. I'm on Linux, though.

**Comment by YordanPetrovDS** [comment]
It wotks with folowing path, but do you have any idea how i can get current project path, i want to make this setting json file, more reusable?
![image](https://user-images.githubusercontent.com/51719948/154807910-a7cfd6f2-f332-4c95-8627-078f1bf98b1b.png)

**Comment by monosans** [comment]
> do you have any idea how i can get current project path, i want to make this setting json file, more reusable?

I suppose there must be a way to get the activated Python venv somewhere in the VSCode API, but I currently have no time to figure it out.

For now, I would recommend creating a separate venv where you will keep djlint.

**Comment by YordanPetrovDS** [comment]
Nevertheless, the extension is awesome! Thank you very much!

**Comment by monosans** [comment]
@YordanPetrovDS I've just released v1.0.0, which supports virtual environments.

**Comment by YordanPetrovDS** [comment]
It works fantastic now!
