### ISSUE TITLE
Max line length option

### ISSUE THREAD

**Issue by YordanPetrovDS** [monosans/djlint-vscode#11]
Is there any way you can add "max_line_length" to be adjustable?

**Comment by monosans** [comment]
I've just opened the issue about it in the `djLint` repository. See https://github.com/Riverside-Healthcare/djLint/issues/190.

**Comment by monosans** [comment]
`max_line_length` can be configured through the configuration file, as indicated in the [corresponding documentation](https://djlint.com/docs/configuration/).
