### ISSUE TITLE
Is it possible to disable the extension for specific file types?

### ISSUE THREAD

**Issue by danstewart** [monosans/djlint-vscode#116]
I like to use the extension when working on jinja within a python environment but when working on nunjucks I don't want the extension to do anything, but every time I save a file I get "djLint is not installed for the current active Python interpreter."

Can I disable the extension for certain file types, or maybe if there is no config file?

**Comment by monosans** [comment]
Hi. These errors appear because linting is running. For now, I can only suggest a separate `.vscode/settings.json' for projects where you want to disable linting. I'll still think about other options.

**Comment by monosans** [comment]
Oops, sorry, the issue isn't fixed after all. I'll fix it now.

**Comment by monosans** [comment]
Fixed in <https://github.com/monosans/djlint-vscode/releases/tag/v2023.7.2>.
