### ISSUE TITLE
Formatting is happening in the background

### ISSUE THREAD

**Issue by yatahaze** [monosans/djlint-vscode#13]
With all the other formatters I've used, I press a keyboard shortcut and the code cleans up on my screen. With this one:

- The file is modified in the background.
- I don't see any changes in my open file. I have to close it and open it again to see anything.
- The "Formatting..." text doesn't show on the vscode status bar.

Is this how it is for everyone else or is something wrong on my end?

**Comment by monosans** [comment]
Hi!

Everything works fine for me with both the "Format Document" shortcut and the "Format On Save" option. I don't even know what I can offer you to help with this.

> The "Formatting..." text doesn't show on the vscode status bar.

I believe this text is generated by the extension you are formatting with. I don't see much point in adding this functionality.

**Comment by yatahaze** [comment]
I'm using the remote extension and working on a remote server, not sure if that plays into this. When I use the option via the menu I get the same results. The file is changed, but not in my open document. I have to close and open to see the changes.

**Comment by monosans** [comment]
I will release a fix for this issue in a couple of hours.

**Comment by monosans** [comment]
The issue should be fixed in version 1.0.6. Please let me know if the fix helped you.

> edits are still made directly and not through the vscode api, right?

Yes, it worked this way before version 1.0.6. Now edits are made via the VSCode API. Thank you very much for the hint and code example.

**Comment by yatahaze** [comment]
Everything works and is integrated into my workflow now. Thanks!!
