### ISSUE TITLE
Indenting broken

### ISSUE THREAD

**Issue by mikekelly1** [monosans/djlint-vscode#14]
I am working through the MDN Django Tutorial and noticed this problem:

```
{% extends "base_generic.django-html" %}
{% block content %}
    <h1>Title: {{ book.title }}</h1>
    <p>
        <strong>Author:</strong><a href="">{{ book.author }}</a>
    </p>
    <p>
        <strong>Summary:</strong> <span>{{ book.summary }}</span>
    </p>
    <p>
        <strong>ISBN:</strong> <span>{{ book.isbn }}</span>
    </p>
{% endblock content %}
{% block content %}
    <h1>Title: {{ book.title }}</h1>
    <p>
        <strong>Author:</strong><a href="">{{ book.author }}</a>
    </p>
    <p>
        {{ book.summary }}
    </p>
    <p>
        {{ book.isbn }}
    </p>
{% endblock content %}
{% block content %}
    <h1>Title: {{ book.title }}</h1>
    <p>
        <strong>Author:</strong><a href="">{{ book.author }}</a>
    </p>
    <p>
        <strong>Summary:</strong> {{ book.summary }}
</p>
<p>
    <strong>ISBN:</strong> {{ book.isbn }}
</p>
{% endblock content %}
```

I have repeated the content block 3 times here to demonstrate the issue. 
The final content block shows the issue. The p tag indentation breaks when they contain a strong tag followed by a variable. 
The top block shows that it works OK if I enclose the variable in a tags or span tags ( I assume any tags would work ). 
The middle block shows that it works if the p tags only contain a variable.

DJLint is the only formatter installed, but I also have the Baptiste Darthenay Django extension installed. My settings.json looks like this:

```
{
    "workbench.colorTheme": "Default Dark+",
    "emmet.includeLanguages": {
        "django-html": "html"
    },
    "files.associations": {
        "*.django-html": "DjangoHTML"
    },
    "[django-html]": {
        "editor.defaultFormatter": "monosans.djlint"
    },
    "editor.minimap.enabled": false,
}
```

**Comment by monosans** [comment]
Hi!

This issue is not related to the VSCode extension, but to djLint itself. 

Please open an issue in [their repository](https://github.com/Riverside-Healthcare/djlint).
