### ISSUE TITLE
Ignore linting tags do not work

### ISSUE THREAD

**Issue by randomsnowflake** [monosans/djlint-vscode#148]
As documented here: https://www.djlint.com/docs/ignoring-code/ 

Adding `{% comment %} djlint:off {% endcomment %}`(or similar) to Django HTML templates does not seem to have any effect.

**Comment by monosans** [comment]
Hi. This repository is specifically for the VSCode extension and your problem is caused directly by djLint itself, which is located here: https://github.com/Riverside-Healthcare/djLint.
