### ISSUE TITLE
Versions 1.0.6-1.0.7 crash Cyrillic

### ISSUE THREAD

**Issue by VladimirMonolith** [monosans/djlint-vscode#17]
Versions 1.0.6-1.0.7 crash Cyrillic symbols in html-templates in VSC.1.0.5 works good.
![Screenshot_2](https://user-images.githubusercontent.com/99643599/163731571-b1b10efb-f635-4249-9529-a6552aa211de.png)

**Comment by monosans** [comment]
I cannot reproduce this error.

![image](https://user-images.githubusercontent.com/76561516/163731729-2d4b8789-cf96-4ae4-8918-7442ca7f387f.png)

Please provide the following information:
- OS;
- File encoding;
- djLint version (`pip freeze`).

**Comment by monosans** [comment]
My friend using Windows has the same problem. Everything works fine for me on Linux. 

So far I don't know how to fix this. Need help.

**Comment by VladimirMonolith** [comment]
> I cannot reproduce this error.
> 
> ![image](https://user-images.githubusercontent.com/76561516/163731729-2d4b8789-cf96-4ae4-8918-7442ca7f387f.png)
> 
> Please provide the following information:
> 
> * OS;
> * File encoding;
> * djLint version (`pip freeze`).

OS - Windows 10
File encoding - UTF-8
djLint version - 1.0.6-7 - break, 1.0.5 - works fine

**Comment by monosans** [comment]
Solution: https://github.com/Riverside-Healthcare/djLint/issues/243#issuecomment-1124603803.

**Comment by monosans** [comment]
Solution - update djLint to version 1.1.1 or higher.
