### ISSUE TITLE
Extension tries to access clipboard

### ISSUE THREAD

**Issue by medihack** [monosans/djlint-vscode#181]
I am using this excellent extension in VS Code on Gitpod (Cloud IDE). Unfortunately, when the extension is enabled and I edit the templates, I always get the message that it tries to access the clipboard (entire message below). As soon as I disable this extension, this message no longer pops up. Does this extension really need access to the clipboard? (Quite problematic as this is not fully supported in Firefox.)

```
Unable to read from the browser's clipboard. Please make sure you have granted access for this website to read from the clipboard.
```

**Comment by monosans** [comment]
Very strange, the extension does not use the clipboard in any way. Maybe djLint does, but I highly doubt it.

Hey, @christopherpickering, what do you think?

**Comment by christopherpickering** [comment]
Hey @monosans , I was just checking this out as well. @monosans is right, there is no clipboard access in djlint through python or through the extension.

It seems like vscode in gitpod uses the clipboard. @medihack what browser + version are you using? I don't have any issues in safari, chrome, and firefix v107.

Have you tested other formatters to see if you get a similar message? 

https://www.gitpod.io/docs/configure/user-settings/browser-settings

**Comment by medihack** [comment]
Hm, that's strange. I could replicate it on two different Windows 11 PCs with Firefox v111.0. It doesn't happen in Chrome. I investigated a bit further. It only happens when both `batisteo.vscode-django` and `monosans.djlint` extensions are enabled (I disabled all other extensions to be sure).
My VS Code settings file also has nothing special. See https://github.com/radexperts/adit/blob/dev/.vscode/settings.json The project is fully open source. So if you have a Gitpod account, you could simply give it a try (just spin up the `dev` brunch in a Gitpod container under FF, open e.g. 404.html and type some stuff in there).

**Comment by medihack** [comment]
Thanks for looking into it. I will investigate it further, try to set up a minimal example and report back.

**Comment by medihack** [comment]
Ok, I tested it a lot now with a minimal example (https://github.com/medihack/djlint-clipboard) and the problem is indeed not the `djlint` extension, but the `batisteo.vscode-django` extension :-( I will open an issue over there, but it seems not too well maintained. Do you perhaps have a good recommendation what syntax highlighter to use for Django templates in VS Code?
And I am really sorry for wasting your time :-( Your extension works excellent.

**Comment by monosans** [comment]
> Do you perhaps have a good recommendation what syntax highlighter to use for Django templates in VS Code?

I use `batisteo.vscode-django`, I have no problems with it. 

> the problem is  the `batisteo.vscode-django` extension

As far as I know, snippets can require access to the clipboard, you can try digging in that direction.
