### ISSUE TITLE
This breaks when formatting a django template with Japanese characters in UTF-8.

### ISSUE THREAD

**Issue by Taikono-Himazin** [monosans/djlint-vscode#20]
This breaks when formatting a django template with Japanese characters in UTF-8.

Before formatting
![image](https://user-images.githubusercontent.com/25480502/168001513-63237d74-5bba-4812-bc5e-763afa08c0d5.png)

After formatting
![image](https://user-images.githubusercontent.com/25480502/168001552-dda0c8ad-f23e-4b5b-9417-d347ba35c81b.png)

Is it possible to increase the option to explicitly specify the character code in settings.json?

Below is my environment.
- OS - Windows 10 Japanese
- File encoding - UTF-8 CRLF
- Python 3.9.10
- djLint version - 1.0.2
- djlint-vscode version - 1.1.0

**Comment by monosans** [comment]
The same thing happens with Cyrillic (#17).

**Comment by Taikono-Himazin** [comment]
Excuse me.
I noticed that the same thing happens when I try it with djlint alone.
This may be a problem with djlint itself, so I reported it to djlint.

**Comment by Taikono-Himazin** [comment]
If you turn on "Beta: Use Unicode UTF-8 with worldwide language support" in the system locale setting of windows, you can do it without any problem.
It seems to be a problem with windows settings. Thank you.

**Comment by monosans** [comment]
Solution - update djLint to version 1.1.1 or higher.

**Comment by Taikono-Himazin** [comment]
After applying this update, it worked fine even if I restored the Windows settings.
