### ISSUE TITLE
Non latin symbols replaced with `????` after formatting in Windows 10.

### ISSUE THREAD

**Issue by Real-Gecko** [monosans/djlint-vscode#22]
If template contains non ASCII symbols after formatting they're replaced with `?` characters. Running djLint directly from command line does not have this issue. So I guess it's somewhere in extension. File encoding is `utf-8`, OS is Windows 10. In Linux and MacOS everything works as expected.

**Comment by monosans** [comment]
Solution: https://github.com/Riverside-Healthcare/djLint/issues/243#issuecomment-1124603803.

**Comment by Real-Gecko** [comment]
Yikes it worked :D
Maybe it should be reflected in a README? so that no one ever asks this question again?

**Comment by Real-Gecko** [comment]
Nah I work on Linux and MacOS, but my colleague are not. I've tired of seeing unformatted templates so :D

**Comment by Real-Gecko** [comment]
OK, after enabling `utf-8` in winduz some other programs has stopped working as expected. So option was turned off again. So, running from command line works as expected, running through extension does not. Maybe we can tweak something on extension side?
Maybe we can add an option to do formatting inplace and ask editor for reload instead of asking it to replace the text in here?
https://github.com/monosans/djlint-vscode/blob/89073365e968effce95dffd99bbf2dc75d2bb579/src/extension.ts#L247
AFAIK some extensions do that, because I have formatting enabled on save, and when I save the file for some time I see file not being formatted, and then suddenly it changes and is resaved. Noticable when you have a lot of files to save at the same time.

**Comment by christopherpickering** [comment]
I'll dust of my windows and take a look tomorrow as well. Do you have a small sample code? I'll try w/ `必須` from the other issue otherwise.

**Comment by Real-Gecko** [comment]
```django
{% extends 'base.html' %}

{% load i18n django_bootstrap5 %}

{% block content %}
<div class="col-4 offset-4 card">
<div class="card card-body">
<form method="post">
{% csrf_token %}
{% bootstrap_form form %}
<button class="btn btn-primary" type="submit">{% trans "Вход" %}</button>
</form>
</div>
</div>
{% endblock content %}
```
This one will do I guess notice the `{% trans "Вход" %}` part.

**Comment by monosans** [comment]
Perhaps [this](https://nodejs.org/api/stream.html#stream_readable_setencoding_encoding) will help solve the issue.  I'll do it today when I'm at home.

**Comment by monosans** [comment]
> AFAIK they use PowerShell as VSCode shell. Don't know what is encoding for this one.

The extension does not launch a shell, but launches Python directly.

**Comment by christopherpickering** [comment]
Windows is being pretty persistent. The colorize library was also allowing windows to tweak the encoding.. so I need to do another update the djlint to ensure the output is passed to the printer as utf8.

I was able to get it to work in vscode, I'll test a bit more and see if anything needs to be pr'ed.

**Comment by monosans** [comment]
> I published djlint 1.1.1, which seems to fix this No changes to djlint-vscode

Amazing! Thank you very much!

I will later write in README.md that djLint version 1.1.1 or higher is required to fix this issue.

**Comment by christopherpickering** [comment]
No problem, thank you!

**Comment by monosans** [comment]
Solution - update djLint to version 1.1.1 or higher.

**Comment by Real-Gecko** [comment]
Hey, guys! We've just checked the update on two machines, one with winduz 10 another with 11. In both cases everything works flawlessly. Thanks for your effort! Really appreciated.
