### ISSUE TITLE
djLint is not installed for the current Python interpreter.

### ISSUE THREAD

**Issue by pors** [monosans/djlint-vscode#23]
Hi!

I get the message `djLint is not installed for the current Python interpreter.`

I use a virtual environment and I have djLint in this environment. In the VS Code terminal (which uses the default environment) djlint works fine.

Any idea how I can fix this?

**Comment by monosans** [comment]
Hi!

What do you use to create a virtual environment (venv, virtualenv, poetry, pipenv)?

What is your VS Code version?

**Comment by monosans** [comment]
Also try running `python -m djlint --version` in VS Code terminal with virtual environment activated.

**Comment by pors** [comment]
VS Code  1.68.0

python -m djlint, version 1.1.1

And I'm using `pyenv` and `pyenv-virtualenv`

**Comment by monosans** [comment]
I couldn't reproduce your problem.

Maybe I'm doing something wrong? Here is a list of commands I used:

```bash
pyenv install 3.10.4
pyenv virtualenv 3.10.4 djlint-venv
source $PYENV_ROOT/versions/3.10.4/envs/djlint-venv/bin/activate
pip install djlint
```

After that, I chose this virtual environment in VS Code, and everything works fine for me.

**Comment by monosans** [comment]
By the way, do you have the `djlint.useVenv` option enabled?

**Comment by pors** [comment]
Yes I had it enabled. I now disabled it and added the full path to the python executable. That works...
