### ISSUE TITLE
Should use vscode's indent spacing

### ISSUE THREAD

**Issue by SmileyChris** [monosans/djlint-vscode#24]
Linting a django-html file with the indentation set to 2 spaces ends up with the standard 4-spaced indentation. 

From reading the [vscode api](https://code.visualstudio.com/api/references/vscode-api#FormattingOptions), it looks like the `provideDocumentFormattingEdits` could accept a `FormattingOptions` object as the second arg which has a `tabSize` property. Then you can use that to populate the `--indent` arg rather than the hard coded (and probably redundant) `djlint.indent` configuration setting.

**Comment by monosans** [comment]
Hi. I thought about your idea, and this is how I decided to realize it.

The current option `djlint.indent` will be completely deleted. Instead, there will be `djlint.indentMode`, consisting of two options. The first option is to take a configuration from a [configuration file](https://djlint.com/docs/configuration/). The second option is to take a setting from VS Code.

What do you think?

**Comment by SmileyChris** [comment]
A boolean option would probably suffice. `djlint.useEditorIndent`
or something (and my preference would be that it defaults to true)

**Comment by monosans** [comment]
Added in [v2022.6.0](https://github.com/monosans/djlint-vscode/releases/tag/v2022.6.0).
