### ISSUE TITLE
Extra blank lines with preserve_blank_lines and blank_line_after_tag

### ISSUE THREAD

**Issue by aarongoldenthal** [monosans/djlint-vscode#26]
Using nunjucks templates with `preserve_blank_lines: true` and format on save, any tag listed in `blank_line_after_tag` has a new blank line inserted after it on every save/format (and in addition to unnecessary whitespace, after 2 saves it will start flagging `H014`).

**Comment by monosans** [comment]
Hi. Are you sure this is an issue with the extension and not with djLint itself? You should open an issue in the [djLint repository](https://github.com/Riverside-Healthcare/djLint) with such problems.

**Comment by aarongoldenthal** [comment]
Good point, I was running djlint without `--reformat`, but trying again with `--reformat` it is a djlint issue.
