### ISSUE TITLE
Support pipx-installed djlint

### ISSUE THREAD

**Issue by dalito** [monosans/djlint-vscode#27]
Thanks for this nice extension!

Typically, I prefer installing general Python tools not in every venv separately but to install them with [pipx](https://pypa.github.io/pipx/) globally. However, djlint-vscode does not execute djlint that is installed by pipx and is on path. If I understand the code correctly, djlint-vscode always executes djlint via `python -m djlint`.

Would it be possible to run djlint directly, e.g. if `djlint.useVenv = false` and `djlint.pythonPath` is not set?

**Comment by monosans** [comment]
Hi. `pipx` creates a separate venv for each application. For example, when I installed djLint, it created a venv for me at `/home/user/.local/pipx/venvs/djlint`. So I can set these settings:

```json
"djlint.useVenv": false,
"djlint.pythonPath": "/home/user/.local/pipx/venvs/djlint/bin/python",
```

Hope that was helpful. Have a good day!

**Comment by dalito** [comment]
Thanks! Yes, pointing to the venv created by pipx works. It is just a bit inconvenient.
