### ISSUE TITLE
djLint is not installed for the current active Python interpreter.

### ISSUE THREAD

**Issue by shaheem-pp** [monosans/djlint-vscode#272]
I have installed djlint globally using pip in my macOS Ventura on my M1 Air. I have also set up the configuration in Visual Studio Code's settings. However, whenever I save a Django HTML file that contains Django templates, I receive the following error message: "djLint is not installed for the current active Python interpreter."

Steps to Reproduce:

1. Install djlint globally using pip.
2. Configure Visual Studio Code to use djlint in the settings.
3. Save a Django HTML file with Django templates.

Expected Behavior:

- The Django HTML file should be successfully linted using djlint without any errors.

Actual Behavior:

- Upon saving the Django HTML file, the error message "djLint is not installed for the current active Python interpreter" is displayed.

Additional Information:

- I am running macOS Ventura on an M1 Air.
- I have verified that djlint is installed globally using pip.
- I have followed the instructions to configure Visual Studio Code to use djlint.
- Other Python-related functionalities in Visual Studio Code are working correctly.

Please let me know if there are any specific steps or configurations I might be missing to resolve this issue. Thank you!

**Comment by stasys-hub** [comment]
I have the same Problem on linux using poetry.  If i disable the useenv flag and set the complete interpreter path, it works. BTW, I am using fish shell. Any suggestions? 
This is pretty annoying when working with multiple projects ...

**Comment by monosans** [comment]
> Any suggestions?

When using the `useVenv` option, you need to make sure that you have the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) installed and that the [appropriate venv is selected in it](https://code.visualstudio.com/docs/python/environments).
