### ISSUE TITLE
Problem on self closing tabs

### ISSUE THREAD

**Issue by danilociaffi** [monosans/djlint-vscode#34]
The extension reports `<hr>`, `<br>` as a problem with message:
```
Tag should be self closing. <hr> (H017)
```

**Comment by monosans** [comment]
Hi.

First, I would like to say that issues of this kind are not related to the extension, but to `djLint` itself.

Second, this issue is not an issue, and `<hr>` and `<br>` should preferably be written as `<hr/>` and `<br/>`.
