### ISSUE TITLE
v2023.8.10 locks up keyboard in vscode.

### ISSUE THREAD

**Issue by haraldnh** [monosans/djlint-vscode#383]
Not quite sure what happens, but after upgrading to the latest version, writing in the editor stops working after a while.  It looks as if it's the djlint command that gets stuck and blocks off something.

Downgrading to v2023.8.7 fixes things, I haven't tried .8 and .9.

VScode 1.81.1 on MacOS.

**Comment by monosans** [comment]
Maybe you are formatting a very large template? I have a template of 1300 lines formatted in 2.5 minutes.

The only change since v2023.8.7 that could have affected this was updating the bundled dependencies.

**Comment by monosans** [comment]
Even when formatting a large file for a long time, my keyboard doesn't lock up. I have no idea why it happens to you.

**Comment by haraldnh** [comment]
Upgraded to v2023.8.10 again now, and after about a minute it gets stuck again.  I get the window saying that it's saving/formatting the 'openapi-ui.html' file (which is the file I'm playing with, and it is 42 lines long).

After leaving it alone for some minutes, I pressed "Cancel" which removed the window.  The keyboard stays stuck, regardless, and there is a "Code helper" process running at 100% cpu which keeps on running also after pressing cancel.

When I kill that Code helper process (regular TERM signal), things come unstuck.  VScode reports "the extension host terminated suddenly" and it seems to clean up.  After this I failed to make things get stuck until restarting VScode again.

I'm not sure, but it _may_ be triggered more reliably if I look at the huge js/css/map files for the swagger-ui before making a change to the template.  So maybe the issue is that the plugin hooks into more than it should when starting up?

**Comment by monosans** [comment]
To be sure that this extension is related to the Code Helper process, please try the following: <https://apple.stackexchange.com/a/393075>.

If you kill djLint process, error logs are recorded. To see the logs, run `workbench.action.showOutputChannels` command in [Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) and select djLint there.
