### ISSUE TITLE
Formatter is appending to file

### ISSUE THREAD

**Issue by samamorgan** [monosans/djlint-vscode#54]
This just started happening today after months of using this plugin. Whenever I save a file, the entire contents of that file are formatted then appended to the end, with messed up formatting in the beginning. For example:

Before
```html
<h1>Heading</h1>
<form method="post" action="{% url 'a_url' %}" class="a_class">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" name="action">Submit</button>
</form>
```

After
```html
<h1>
Heading
</h1>
<form method="post" action="{% url 'a_url' %}" class="a_class">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="action">
Submit
</button>
</form>

<h1>Heading</h1>
<form method="post" action="{% url 'a_url' %}" class="a_class">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" name="action">Submit</button>
</form>
```

From what I can tell, there have been no updates or environment changes in the past day.

### Environment
Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by samamorgan** [comment]
Also mentioned this in the DJLint thread. Unsure of where the fault lies here, but if I roll back to `djlint==1.12.0` the issue goes away. A commenter on that thread noted:

https://github.com/Riverside-Healthcare/djLint/issues/359#issuecomment-1232952888
> It sounds like djlint isn't being called correctly.

**Comment by monosans** [comment]
Fixed in https://github.com/Riverside-Healthcare/djLint/pull/361.

**Comment by monosans** [comment]
Added a note to the README with a solution to this problem - https://github.com/monosans/djlint-vscode/commit/8996069b139e899b2ca5127527dd4ffe8460eb8b.
