### ISSUE TITLE
No ignore option

### ISSUE THREAD

**Issue by kanneg881** [monosans/djlint-vscode#8]
There is no ignore option for djlint

-i, --ignore TEXT     Codes to ignore. ex: "H014,H017"

It is better in setting.json

like this

```
{
    "djlint.ignore": "H014,H017",
}
```

or

```
{
    "djlint.ignore": ["H014", "H017"],
}
```

**Comment by monosans** [comment]
Hi!

Thank you for the suggestion.

This feature is now available in version 0.2.0.

At the moment, I can't log in to my Microsoft account, so the release of the update in the marketplace will be slightly delayed.

For now, you can download the VSIX file from [here](https://github.com/monosans/djlint-vscode/releases/tag/v0.2.0).
