### ISSUE TITLE
Formatter not working when pyproject.toml not at project root

### ISSUE THREAD

**Issue by fabien-michel** [monosans/djlint-vscode#81]
My project dir structure is like this:
```
/project
/project/django
/project/django/pyproject.toml
/project/django/app/template/blop.html
```

The djlint config is inside `pyproject.toml` :
```toml
[tool.djlint]
profile="django"
max_line_length=120
indent=2
blank_line_after_tag="load,extends,include"
```

The `blop.html` file language mode is `django-html`

When running djlint from command line it work as expected:
```[/absolute/path/to/project/]$ djlint --reformat django/app/template/blop.html```

But when running the formatter from vscode it seems to apply a default configuration (`blank_line_after_tag` is not respected)

I'v tried to force djlint configuration in vscode config but it still doesn't work:
```json
{
  "djlint.useEditorIndentation": false,
  "djlint.configuration": "/absolute/path/to/project/django/pyproject.toml"
}
```

The only way I've found so far to have it working is to put `pyproject.toml` at project root. But it is not a nice solution for me.

Other notes:
 * There is a python venv. Workspace is configured to use it.
 * `djlint 1.19.0` is installed inside the venv

Did I miss something ? How to have djlint-vscode respect my pyproject.toml file ?
By the way there is a way to have logs of what djlint-vscode is doing ?

**Comment by christopherpickering** [comment]
I wonder if this
![image](https://user-images.githubusercontent.com/17788706/195575100-abfbd97e-026a-4335-bc86-791b129ceb71.png)

should be the directory of the current file, not the project root?

Right now it is the directory that is opened in VSCode. If it were to use the current file directory it will probably work.

I'm not sure if this is the right vs command, but `vscode.window.activeTextEditor.document.uri.fsPath` sounds like it would work.

**Comment by christopherpickering** [comment]
@monosans  Easier said than done lol, I found a way that works and uses the pyproject.toml file correctly. I'll put a PR for you.

**Comment by monosans** [comment]
Fixed in [v2022.10.0](https://github.com/monosans/djlint-vscode/releases/tag/v2022.10.0). Many thanks to @christopherpickering for the help and quick fix!

**Comment by fabien-michel** [comment]
Thanks for he fast fix ! It solve the issue main issue for me without having to specify the configuration file.
Nevertheless, it don't explain why specifying the configuration file make it not used by djlint.

**Comment by monosans** [comment]
> Nevertheless, it don't explain why specifying the configuration file make it not used by djlint.

AFAIK `--configuration` doesn't support pyproject.toml, only `.djlintrc` format.

**Comment by christopherpickering** [comment]
@monosans thats correct, sorry I didn't notice that @fabien-michel.

**Comment by monosans** [comment]
> By the way there is a way to have logs of what djlint-vscode is doing ?

The error logs are in Developer Tools (Ctrl+Shift+I or Help > Toggle Developer Tools).
