### ISSUE TITLE
Configuration from pyproject.toml is being ignore in v2022.10.1

### ISSUE THREAD

**Issue by marco-galaviz-infront** [monosans/djlint-vscode#83]
After updating to v2022.10.1, extension started displaying problems in base.html that I was ignoring in config file.
`Consider adding a meta description. <html lang="en">  (H030)`
`Consider adding meta keywords. <html lang="en">  (H031)`

My project has the pyproject.toml at root level with config values for djliint:
```
[tool.djlint] 
ignore = "H005,H030,H031,H021,T002,D018" 
profile = "django" 
use_gitignore = true 
```
I'm using Poetry venv 1.1.13 with djlint v1.7.0 and extension v2022.10.1.
I tried updating djlint to the latest version v1.19.1 but no luck fixing the problem.

**Comment by monosans** [comment]
Hi! Can you please show me your folder hierarchy so I can try to reproduce this? I need to know where the templates are relative to pyproject.toml.

**Comment by marco-galaviz-infront** [comment]
I'm using a project level templates folder.
```
.
+-- app1/
|   +-- ...
+-- templates/
|   +-- app1/
|   |   +-- template.html
|   +-- base.html
+-- manage.py
+-- pyproject.toml
```

**Comment by monosans** [comment]
Tried identical file hierarchy. Everything works. Any thoughts on this? How is your environment different from mine?

**Comment by marco-galaviz-infront** [comment]
I'm clueless about what could be the issue with my setup and the latest version.
I'm using python 3.9.10 (using Poetry 1.1.13 venv), djlint 1.7.0, djlint-vscode 2022.10.1 (the issue it's gone if I go back to 2022.09.0).

Using djlint cli with previously metioned configuration works without errors.
I tried switching to .djlintrc config file but it had no effect.
I have no custom extension settings except editor.defaultFormatter in my workspace .vscode/settings.json (as recommended)
```
    "[html]": {
        "editor.defaultFormatter": "monosans.djlint"
    },
    "[django-html]": {
        "editor.defaultFormatter": "monosans.djlint"
    }
```
And errors are **effectively ignored** if i set codes in extension setting djlint.ignore:
```
"djlint.ignore": [
  "H030",
  "H031"
]
```

**Comment by christopherpickering** [comment]
@marco-galaviz-infront what OS are you using?

**Comment by marco-galaviz-infront** [comment]
Windows10 Pro, I can't get the exact version right now in case its needed.
Also mentioning I have batisteo.vscode-django installed and using django-html language mode, and changing to html doesnt affect, but why would it be the case.

Honestly it might come to the fact that my project is dragging some updates released by djlint, I'm currently checking the change log since 1.7.0 to the latest release, but just updating to 1.19.1 doesnt fix the issue.

**Comment by marco-galaviz-infront** [comment]
This is the base.html file that triggers H030 and H031 errors. 
```
{% load static %}
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="{% static 'img/favicon.svg' %}" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
              crossorigin="anonymous"/>
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"/>
        <!-- Alpine initial x-cloak style -->
        <style>[x-cloak] { display: none !important; }</style>
        {% block head_scripts %}
        {% endblock head_scripts %}
    </head>
    <body class="d-flex flex-column min-vh-100">
        {% block content %}
        {% endblock content %}
    </body>
</html>

```

**Comment by marco-galaviz-infront** [comment]
@christopherpickering @monosans 
I have created a [testing repo](https://github.com/marco-galaviz-infront/djlint-test) and errors prevailed.

Do you set your Python Interpreter to your virtual env python in vscode?
I have tested it in a different "clean" windows machine and the errors are still present.
Environment info:
- Windows 10 Pro (NT x64 10.0.19044)
- Visual Studio Code 1.72.2
- Python 3.9.10
- djlint 1.19.1
- djlint-vscode 2022.10.1
- ms-python.python 2022.16.1

**Comment by monosans** [comment]
Are you aware that VSCode setting `djlint.ignore` overrides the `ignore` setting in pyproject.toml?

**Comment by marco-galaviz-infront** [comment]
> Are you aware that VSCode setting `djlint.ignore` overrides the `ignore` setting in pyproject.toml?

Yes, but unless I have to manually disable or modify the djlint.ignore by default, it shouldnt be the problem.

I'll leave here my User settings in case there is some conflict I'm not seeing.
```
{
    "editor.quickSuggestionsDelay": 50,
    "editor.quickSuggestions": {
        "other": "on",
        "comments": "off",
        "strings": "off"
    },
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.inlayHints.enabled": "onUnlessPressed",
    "editor.guides.highlightActiveIndentation": "always",
    "editor.suggestOnTriggerCharacters": true,
    "editor.suggest.localityBonus": true,
    "editor.suggest.preview": true,
    "diffEditor.wordWrap": "off",
    "diffEditor.ignoreTrimWhitespace": false,
    "notebook.lineNumbers": "on",
    "prettier.insertPragma": false,
    "prettier.tabWidth": 4,
    "prettier.singleQuote": true,
    "prettier.enableDebugLogs": true,
    "window.confirmBeforeClose": "always",
    "workbench.colorTheme": "Monokai Pro (Filter Spectrum)",
    "workbench.iconTheme": "material-icon-theme",
    "vsicons.dontShowNewVersionMessage": true,
    "material-icon-theme.hidesExplorerArrows": true,
    "files.refactoring.autoSave": true,
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "html.format.enable": false,
    "html.format.templating": true,
    "emmet.triggerExpansionOnTab": true,
    "emmet.includeLanguages": {
        "django-html": "html",
        "javascript": "django-html"
    },
    "css.enabledLanguages": ["django-html", "html"],
    "css.styleSheets": [
        "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css",
        "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"
    ],
    "[python]": {
        "editor.defaultFormatter": "ms-python.python",
        "editor.bracketPairColorization.enabled": true
    },
    "python.formatting.provider": "black",
    "python.terminal.activateEnvInCurrentTerminal": true,
    "python.terminal.activateEnvironment": true,
    "jupyter.askForKernelRestart": true,
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": true,
    "javascript.format.insertSpaceAfterConstructor": true,
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.enableBell": true,
    "terminal.integrated.defaultProfile.windows": "Windows PowerShell",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        },
        "Windows PowerShell": {
            "path": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        }
    },
    "git.suggestSmartCommit": false,
    "git-graph.repository.fetchAndPrune": true
}
```

**Comment by marco-galaviz-infront** [comment]
Hi again! I discover that switching from python interpreter 3.9.10 to 3.10.5 (python extension in vscode) fixes the problem; the ignore setting is effectively readed from pyproject.toml.

Python 3.9.10 (Poetry venv) interpreter selected:
![image](https://user-images.githubusercontent.com/86737781/196528511-7a13effd-7297-46bc-987b-4d4b79668ef3.png)

Python 3.10.5 (Poetry venv) interpreter selected:
![image](https://user-images.githubusercontent.com/86737781/196528623-5778fe64-4e9a-4a1a-81ef-6a70880cf1a2.png)

If you have any further thoughts or suggestions, I'm open to keep looking into this, but I guess I'll just bump python to 3.10 to continue using the extension.

**Comment by christopherpickering** [comment]
Ah interesting! Is the same djlint version installed in both pythons?

**Comment by marco-galaviz-infront** [comment]
@monosans I have djlint latest version, also tried different python 3.9.x but it didn't work, and 3.10.x fixes the issue.
I compared the djlint dependencies in both 3.9 and 3.10 but there wasn't any difference.

**Comment by Egil-nov** [comment]
I have the same issue: The pyproject.toml file in the root is ignored with djlint-vscode v2022.10.1 and Python 3.9 but works in Python 3.10 and/or djlint-vscode v2022.9.0.

The same djlint version is installed in both environments.

**Comment by christopherpickering** [comment]
hmm interesting, what minor version of 3.9? I'll try to debug more.

**Comment by Egil-nov** [comment]
The issue also affects 3.9.7, which I am using.

**Comment by christopherpickering** [comment]
Thanks, you are windows 10 as well right?

**Comment by christopherpickering** [comment]
I'm able to reproduce in vs code.
- Running w/ pyenv 3.10 > works
- Changing to pyenv 3.9 > fails (3 errors show up)
- Using the same env in the terminal > works, 1 error show up

After digging more it seems like py3.9 "sometimes" treats a path of "-" as the system root, and sometimes as the current dir.

I will publish a djlint update to specify that "-" (the path used in vscode and other headless implementations) is the current dir.

**Comment by marco-galaviz-infront** [comment]
@christopherpickering I just tested the new release and the issue is gone now! Great work, thanks!
